### ISSUE TITLE
Collapse navigation at larger breakpoint and include login/signup buttons

### ISSUE THREAD

**Issue by noeldevelops** [thedigitalgarage/hugo-market-theme#3]
Navigation links collapse to a 'hamburger' icon at 768px on marketplace, but on thedigitalgarage.io they are visible only <1200px.  A good compromise maybe - collapse below 1026px? @johnmccawley  is there a preference?

**Comment by johnmccawley** [comment]
For now, let's keep it consistent with the landing page theme. We will be doing a re-design in the coming months so it would be good to make this as consistent as possible.

**Comment by noeldevelops** [comment]
ok I will make sure the breakpoints are the same as the landing page
