### ISSUE TITLE
Add a footer to marketplace

### ISSUE THREAD

**Issue by noeldevelops** [thedigitalgarage/hugo-market-theme#4]
Do we need/want a footer? Could include the register and login links as well as other info...

**Comment by johnmccawley** [comment]
Hi Noel @anc02d , I agree that the marketplace should have a footer. Let's make the composition the same as the footer on the landing page. (see the image below)

![image](https://user-images.githubusercontent.com/14791640/29294109-f484b0ac-810a-11e7-8b15-61fd1fa5644f.png)

You should have access to the TDG Landing Website repo. It is an AngularJS app for the landing page. Here is the url for the footer.

https://github.com/thedigitalgarage/tdg-landing-website/tree/development/views/includes/footer.pug

**Comment by noeldevelops** [comment]
footer is close to done, but  where do the white border lines next to footer links come from? I can't locate in stylesheet
