### ISSUE TITLE
Add Login and Sign Up Links to Marketplace

### ISSUE THREAD

**Issue by noeldevelops** [thedigitalgarage/hugo-market-theme#5]
Both the Login and Sign Up buttons need to be redirected to the correct URL. They need to be included in the drop down menu on smaller screens

**Comment by johnmccawley** [comment]
@EddSuarez , Would you take a quick look at the marketplace template that Noel has created? We have login and sign-up links at the top. It would be great to have a consistent behavior on these links.

**Comment by EddSuarez** [comment]
sure, @johnmccawley
