### ISSUE TITLE
Revise Cards on Marketplace Home

### ISSUE THREAD

**Issue by johnmccawley** [thedigitalgarage/hugo-market-theme#8]
In the cards on the marketplace home we should make the logos twice the current size, The Title should be large and centered to the Logo. Add at least 10 px of padding between the logo/title line and the description.

![image](https://user-images.githubusercontent.com/14791640/29294661-c1c60366-810d-11e7-8daf-796c6ea58759.png)

**Comment by noeldevelops** [comment]
![screen shot 2017-08-16 at 11 25 41 am](https://user-images.githubusercontent.com/20971470/29376409-afe637ce-8275-11e7-83d7-2fde5b9fad1b.png)

Getting better... I'm wondering if we should 
1. force an exact height and hide overflow so all cards are exactly the same size?
2.  hide name _and_ description on screens < 768px ?  e.g.: 
![screen shot 2017-08-16 at 11 27 54 am](https://user-images.githubusercontent.com/20971470/29376499-fb27e23c-8275-11e7-8fb5-33116c68682b.png)

(previously only the description was being hidden on smaller screens)
@johnmccawley let me know what you think

Also, I am going to upload more items/content so I can see what it looks like with all categories and several cards in each category

**Comment by johnmccawley** [comment]
Hi @anc02d, I agree. Hide title and description on small screens. If a logo does not exist we would display title. Great idea!

**Comment by noeldevelops** [comment]
hm I wasn't thinking about what to do if the logo doesn't exist. I will make this a separate issue as I'm not sure yet how to implement that logic - currently it's just a `display:none` in the CSS file
